name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.newsAPIkey }}  # Set the environment variable from the secret

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use the API Key
        run: |
          # Access the API key from the environment variable
          echo "API Key is $API_KEY"

      - name: Build and Deploy
        run: |
          # Use the API key in your build or deployment process
          # For example, you can set it as an environment variable for your application
          export MY_APP_API_KEY=$API_KEY
          # Continue with your build and deployment steps

